---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.3.7"}]
  synced_folders:
    - ["./", "/vagrant"]


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      customize:
        memory: 1024

suites:
  - name: default
    run_list:
      - role[magento]
    attributes:
